export default {
  '__DEV__': 'readonly',
  '__TEST__': 'readonly',
  'log': 'readonly',
  'dev': 'readonly',
  'timers': 'readonly',
  'defineRule': 'readonly',
  'defineAlias': 'readonly',
  'defineVirtualDevice': 'readonly',
  'getDevice': 'readonly',
  'getControl': 'readonly',
  'startTicker': 'readonly',
  'startTimer': 'readonly',
  'spawn': 'readonly',
  'runShellCommand': 'readonly',
  'readConfig': 'readonly',
  'trackMqtt': 'readonly',
  'publish': 'readonly',
  'PersistentStorage': 'readonly',
  'Notify': 'readonly',
}
