name: Feature Request
description: Предложите идею для этого проекта
labels: [triage, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что уделяете время заполнению данного запроса. Обратите внимание, шаблон предназначен только для запросов дополнительного функционала. Используйте раздел [GitHub Discussions](https://github.com/wb-mirta/core/discussions) при возникновении каких-либо вопросов.
  - type: textarea
    id: related-problem
    attributes:
      label: Ваш запрос связан с проблемой?
      description: Пожалуйста, предоставьте чёткое и лаконичное описание проблемы.
      placeholder: Опишите проблему, с которой пришлось столкнуться!
  - type: textarea
    id: expected-behavior
    attributes:
      label: Опишите предпочтительное решение
      description: Пожалуйста, предоставьте чёткое и лаконичное описание решения.
      placeholder: Опишите Ваш запрос!
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Уже видели эту реализацию где-нибудь?
      description: Пожалуйста, по возможности предоставьте примеры использования, ссылки на методические материалы, скриншоты или видео ожидаемого результата.
      placeholder: Покажите нам примеры!
  - type: textarea
    id: alternatives
    attributes:
      label: Опишите альтернативные варианты, которые Вы рассматривали
      description: Пожалуйста, предоставьте чёткое и лаконичное описание любых альтернативных решений или функций, которые Вы рассматривали.
      placeholder: Опишите альтернативы!
  - type: checkboxes
    id: pr
    attributes:
      label: Pull Request
      description: Если вы хотите увидеть этот функционал в ближайшее время, рассмотрите возможность отправки запроса на внесение изменений. Вклад сообщества в развитие проекта очень ценен!
      options:
        - label: Я планирую подготовить Pull Request
