name: Build

on:
  push:
    branches:
      - latest
  pull_request:
    branches:
      - latest

jobs:
  test:
    if: ${{ !startsWith(github.event.head_commit.message, 'release') }}
    uses: ./.github/workflows/test.yml
  build:
    # Prevents this action from running on forks.
    if: github.repository == 'wb-mirta/core'
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Continuous Release
        # Prevents this step from running on pull requests.
        # Runs only when commit message starts with 'fix' or 'feat'.
        if: |
          github.event_name == 'push' && (
            startsWith(github.event.head_commit.message, 'fix') ||
            startsWith(github.event.head_commit.message, 'feat')
          )
        run: pnpx pkg-pr-new publish --compact --pnpm './packages/*' --no-template
